### PR TITLE
Limelight Trig Rangefinding

### PR DESCRIPTION
**Pull request by ghost**
PR for everything about the shooter.

Includes:
- falcon PIDV
- Limelight distance calculation (using area and regressions)
- May include PhotonVision depending on its necessity for Auton.

todo:
- [ ] More data points because Justin got mad (half a foot?)
- [ ] Real PIDV tuning with an actual goal - this will include putting values into the shooter tables.
- [ ] remove i gain

### CODE REVIEW

**Comment by ghost** [comment]
We should probably use PhotonVision, and the trig

with a high resolution the calculation is much more accurate

**Comment by ghost** [comment]
https://www.chiefdelphi.com/t/limelight-distance-calculation-process-question/403297

**Comment by gabeseq** [comment]
leaving cr/shooter branch for future shooting development

**Comment by ghost** [comment]
gonna try prateek method to increase accuracy

**Pull request merged**
